"""
Intent Router Agent for ZICO.

This module provides the first AI-driven agent node in the ZICO travel operations
architecture. It inspects incoming user queries and classifies them into one of four
standardized operational intents:
    - 'flight': Aviation, flight status, schedules, delays, and airport operations.
    - 'research': Factual travel research, live policies, visa rules, and restrictions.
    - 'general_travel': Broad itinerary planning, packing lists, and general travel tips.
    - 'unsupported': Requests outside the scope of travel and aviation operations.

Design Principles:
    - Deterministic & Structured: Uses structured output via `RouterDecision`.
    - No Business/Tool Logic: Strictly classifies requests; never calls tools.
    - Centralized LLM: Instantiates models solely through `app.core.llm.get_chat_model`.
    - Safe Error Handling: Falls back to 'unsupported' and logs errors without crashing.
    - LangGraph Compatible: Consumes `TravelState` and returns partial state updates.
"""

from __future__ import annotations

from typing import Any, Dict, Literal, Optional, Set

from langchain_core.messages import HumanMessage, SystemMessage
from pydantic import BaseModel, Field

from app.core.llm import get_chat_model
from app.core.logging import get_logger
from app.core.state import TravelState

logger = get_logger(__name__)

# The four authoritative operational intents supported by ZICO
AllowedIntent = Literal["flight", "research", "general_travel", "unsupported"]
ALLOWED_INTENTS: Set[str] = {"flight", "research", "general_travel", "unsupported"}

# Conservative, deterministic system prompt for intent routing
ROUTER_SYSTEM_PROMPT = """You are ZICO's Travel Intent Router Agent.
Your role is to classify the user's travel request into exactly one operational category.

Allowed Categories:
1. "flight": Requests concerning flights, aviation status, schedules, delays, routes, airlines, or airport flight tracking (e.g. "Check flight EK522", "Is my flight delayed?", "Find flights from TRV to DXB", "Status of flight AI123").
2. "research": Requests requiring current factual travel research, government regulations, visa policies, travel advisories, entry restrictions, or airline baggage allowances (e.g. "What are the visa requirements for Germany?", "Is Dubai airport open today?", "What is the baggage limit for Emirates?").
3. "general_travel": Broad trip planning, packing advice, general destination suggestions, or multi-day trip ideas not requiring specific flight status or live regulatory policy research (e.g. "Help me plan a 7-day trip to Paris", "What should I pack for Dubai?").
4. "unsupported": Requests that clearly fall outside the domain of travel, aviation, or trip operations (e.g. writing software, math problems, medical diagnoses, general knowledge outside travel).

Guidelines:
- Return exactly one category from the four allowed values.
- If a request requires live or external policy information (like visa rules), choose "research".
- Do NOT perform or execute any operations or tools.
- Return output strictly conforming to the required schema."""


# ---------------------------------------------------------------------------
# Structured Output Model
# ---------------------------------------------------------------------------


class RouterDecision(BaseModel):
    """
    Structured classification decision generated by the Router Agent.
    """

    intent: AllowedIntent = Field(
        description="The selected operational travel intent."
    )
    confidence: Optional[float] = Field(
        default=1.0,
        description="Heuristic model assessment of intent confidence (0.0 to 1.0).",
    )


# ---------------------------------------------------------------------------
# Router Agent Implementation
# ---------------------------------------------------------------------------


class RouterAgent:
    """
    Agent responsible for classifying user queries into operational travel intents.
    """

    def __init__(self, model: Optional[Any] = None) -> None:
        """
        Initialize the Router Agent.

        Args:
            model: Optional pre-configured chat model override (useful for testing).
                   If omitted, defaults to the centralized model from `get_chat_model()`.
        """
        self._model = model

    def _get_model(self) -> Any:
        """Resolve the active chat model instance."""
        if self._model is not None:
            return self._model
        return get_chat_model()

    def route(self, state: TravelState) -> Dict[str, Any]:
        """
        Execute intent routing on the provided TravelState.

        Args:
            state: Active TravelState containing `user_query`.

        Returns:
            Partial state update dictionary containing `intent`, `intent_confidence`,
            and `active_agent`.
        """
        # 1. Validate user query
        user_query = state.get("user_query") if isinstance(state, dict) else getattr(state, "user_query", None)
        if not user_query or not isinstance(user_query, str) or not user_query.strip():
            logger.warning("Router received empty or missing user query; classifying as unsupported.")
            return {
                "intent": "unsupported",
                "intent_confidence": None,
                "active_agent": "router_agent",
            }

        cleaned_query = user_query.strip()
        logger.info("Routing user request (query_len=%d)", len(cleaned_query))

        # 2. Obtain model
        try:
            model = self._get_model()
        except Exception as exc:
            logger.error("Failed to obtain chat model for routing: %s", exc)
            current_errors = list(state.get("errors", [])) if isinstance(state, dict) else []
            return {
                "intent": "unsupported",
                "intent_confidence": None,
                "active_agent": "router_agent",
                "errors": current_errors + [f"Router LLM configuration error: {exc}"],
            }

        # 3. Bind structured output schema
        if hasattr(model, "with_structured_output"):
            runnable = model.with_structured_output(RouterDecision)
        else:
            runnable = model

        # 4. Invoke model with structured prompt
        messages = [
            SystemMessage(content=ROUTER_SYSTEM_PROMPT),
            HumanMessage(content=cleaned_query),
        ]

        try:
            response = runnable.invoke(messages)
        except Exception as exc:
            logger.error("Router model invocation failed: %s", exc)
            current_errors = list(state.get("errors", [])) if isinstance(state, dict) else []
            return {
                "intent": "unsupported",
                "intent_confidence": None,
                "active_agent": "router_agent",
                "errors": current_errors + [f"Router model failure: {exc}"],
            }

        # 5. Parse and validate structured output
        decision: Optional[RouterDecision] = None

        if isinstance(response, RouterDecision):
            decision = response
        elif isinstance(response, dict):
            try:
                decision = RouterDecision(**response)
            except Exception as exc:
                invalid_intent = str(response.get("intent", "unknown"))
                logger.warning("Router model returned invalid intent dictionary %r: %s", response, exc)
                current_errors = list(state.get("errors", [])) if isinstance(state, dict) else []
                return {
                    "intent": "unsupported",
                    "intent_confidence": None,
                    "active_agent": "router_agent",
                    "errors": current_errors + [f"Invalid intent '{invalid_intent}'; fell back to unsupported."],
                }
        elif hasattr(response, "parsed"):
            parsed = getattr(response, "parsed")
            if isinstance(parsed, RouterDecision):
                decision = parsed
            elif isinstance(parsed, dict):
                try:
                    decision = RouterDecision(**parsed)
                except Exception:
                    decision = None

        if decision is None:
            logger.error("Router received unparseable response structure: %r", response)
            current_errors = list(state.get("errors", [])) if isinstance(state, dict) else []
            return {
                "intent": "unsupported",
                "intent_confidence": None,
                "active_agent": "router_agent",
                "errors": current_errors + ["Model failed to produce a valid RouterDecision."],
            }

        # 6. Strict validation against allowed intents
        if decision.intent not in ALLOWED_INTENTS:
            logger.warning("Router received intent %r outside allowed categories.", decision.intent)
            current_errors = list(state.get("errors", [])) if isinstance(state, dict) else []
            return {
                "intent": "unsupported",
                "intent_confidence": None,
                "active_agent": "router_agent",
                "errors": current_errors + [f"Unrecognized intent '{decision.intent}'; fell back to unsupported."],
            }

        logger.info("Router selected intent: %s (confidence=%s)", decision.intent, decision.confidence)
        return {
            "intent": decision.intent,
            "intent_confidence": decision.confidence,
            "active_agent": "router_agent",
        }

    async def aroute(self, state: TravelState) -> Dict[str, Any]:
        """
        Asynchronously execute intent routing on the provided TravelState.

        Args:
            state: Active TravelState containing `user_query`.

        Returns:
            Partial state update dictionary.
        """
        # 1. Validate user query
        user_query = state.get("user_query") if isinstance(state, dict) else getattr(state, "user_query", None)
        if not user_query or not isinstance(user_query, str) or not user_query.strip():
            logger.warning("Router received empty or missing user query; classifying as unsupported.")
            return {
                "intent": "unsupported",
                "intent_confidence": None,
                "active_agent": "router_agent",
            }

        cleaned_query = user_query.strip()
        logger.info("Routing user request asynchronously (query_len=%d)", len(cleaned_query))

        # 2. Obtain model
        try:
            model = self._get_model()
        except Exception as exc:
            logger.error("Failed to obtain chat model for routing: %s", exc)
            current_errors = list(state.get("errors", [])) if isinstance(state, dict) else []
            return {
                "intent": "unsupported",
                "intent_confidence": None,
                "active_agent": "router_agent",
                "errors": current_errors + [f"Router LLM configuration error: {exc}"],
            }

        # 3. Bind structured output schema
        if hasattr(model, "with_structured_output"):
            runnable = model.with_structured_output(RouterDecision)
        else:
            runnable = model

        # 4. Invoke model asynchronously
        messages = [
            SystemMessage(content=ROUTER_SYSTEM_PROMPT),
            HumanMessage(content=cleaned_query),
        ]

        try:
            if hasattr(runnable, "ainvoke"):
                response = await runnable.ainvoke(messages)
            else:
                response = runnable.invoke(messages)
        except Exception as exc:
            logger.error("Router async model invocation failed: %s", exc)
            current_errors = list(state.get("errors", [])) if isinstance(state, dict) else []
            return {
                "intent": "unsupported",
                "intent_confidence": None,
                "active_agent": "router_agent",
                "errors": current_errors + [f"Router model failure: {exc}"],
            }

        # 5. Parse and validate structured output
        decision: Optional[RouterDecision] = None
        if isinstance(response, RouterDecision):
            decision = response
        elif isinstance(response, dict):
            try:
                decision = RouterDecision(**response)
            except Exception as exc:
                invalid_intent = str(response.get("intent", "unknown"))
                current_errors = list(state.get("errors", [])) if isinstance(state, dict) else []
                return {
                    "intent": "unsupported",
                    "intent_confidence": None,
                    "active_agent": "router_agent",
                    "errors": current_errors + [f"Invalid intent '{invalid_intent}'; fell back to unsupported."],
                }
        elif hasattr(response, "parsed"):
            parsed = getattr(response, "parsed")
            if isinstance(parsed, RouterDecision):
                decision = parsed
            elif isinstance(parsed, dict):
                try:
                    decision = RouterDecision(**parsed)
                except Exception:
                    decision = None

        if decision is None or decision.intent not in ALLOWED_INTENTS:
            unrec = decision.intent if decision else "unparseable"
            logger.warning("Router received invalid intent %r.", unrec)
            current_errors = list(state.get("errors", [])) if isinstance(state, dict) else []
            return {
                "intent": "unsupported",
                "intent_confidence": None,
                "active_agent": "router_agent",
                "errors": current_errors + [f"Unrecognized intent '{unrec}'; fell back to unsupported."],
            }

        logger.info("Router selected intent: %s (confidence=%s)", decision.intent, decision.confidence)
        return {
            "intent": decision.intent,
            "intent_confidence": decision.confidence,
            "active_agent": "router_agent",
        }


# ---------------------------------------------------------------------------
# Module-level Convenience Functions (LangGraph Node Interface)
# ---------------------------------------------------------------------------


def route_request(state: TravelState, llm: Optional[Any] = None) -> Dict[str, Any]:
    """
    Synchronous LangGraph node function for request intent routing.

    Args:
        state: Active TravelState containing `user_query`.
        llm: Optional pre-configured chat model override.

    Returns:
        Partial state update dictionary containing classified `intent`.
    """
    agent = RouterAgent(model=llm)
    return agent.route(state)


async def aroute_request(state: TravelState, llm: Optional[Any] = None) -> Dict[str, Any]:
    """
    Asynchronous LangGraph node function for request intent routing.

    Args:
        state: Active TravelState containing `user_query`.
        llm: Optional pre-configured chat model override.

    Returns:
        Partial state update dictionary containing classified `intent`.
    """
    agent = RouterAgent(model=llm)
    return await agent.aroute(state)
