"""
Intent Router Agent for ZICO.

This module provides the first AI-driven agent node in the ZICO travel operations
architecture. It inspects incoming user queries and classifies them into structured
operational intents:
    - 'FLIGHT_SEARCH' / 'flight': Finding flight tickets, schedules, routes, airlines, options.
    - 'FLIGHT_STATUS': Live tracking, status, delay checks, gate/terminal inquiries.
    - 'HOTEL_SEARCH': Finding hotels, resorts, homestays, accommodations, room rates, and budgets.
    - 'DESTINATION_RESEARCH' / 'research': Factual travel research, attractions, guides, advisories.
    - 'ITINERARY_PLANNING': Multi-day trip planning and schedules.
    - 'TRAVEL_POLICY': Baggage allowances, visa rules, EU261 compensation, passport validity.
    - 'LOCATION_QUERY': Geographic coordinates, nearest airports, transit distances.
    - 'GENERAL_TRAVEL' / 'general_travel': Broad travel tips, packing advice, and suggestions.
    - 'UNSUPPORTED' / 'unsupported': Requests outside travel, aviation, or trip operations.

Design Principles:
    - Deterministic & Structured: Uses structured output via `RouterDecision`.
    - No Hallucination: Never invents destinations, origins, or flight routes for hotel/research queries.
    - Safe Error Handling: Falls back to 'unsupported' upon invalid intents without crashing.
    - LangGraph Compatible: Consumes `TravelState` and returns partial state updates.
"""

from __future__ import annotations

import re
from typing import Any, Dict, Literal, Optional, Set

from langchain_core.messages import HumanMessage, SystemMessage
from pydantic import BaseModel, Field

from app.core.llm import get_chat_model
from app.core.logging import get_logger
from app.core.state import TravelState

logger = get_logger(__name__)

# Authoritative operational intents supported by ZICO
AllowedIntent = Literal[
    "FLIGHT_SEARCH",
    "FLIGHT_STATUS",
    "HOTEL_SEARCH",
    "DESTINATION_RESEARCH",
    "ITINERARY_PLANNING",
    "TRAVEL_POLICY",
    "LOCATION_QUERY",
    "GENERAL_TRAVEL",
    "UNSUPPORTED",
    # Legacy lowercase variants
    "flight",
    "research",
    "general_travel",
    "unsupported",
]

ALLOWED_INTENTS: Set[str] = {
    "FLIGHT_SEARCH",
    "FLIGHT_STATUS",
    "HOTEL_SEARCH",
    "DESTINATION_RESEARCH",
    "ITINERARY_PLANNING",
    "TRAVEL_POLICY",
    "LOCATION_QUERY",
    "GENERAL_TRAVEL",
    "UNSUPPORTED",
    "flight",
    "research",
    "general_travel",
    "unsupported",
}

# Conservative, deterministic system prompt for intent routing
ROUTER_SYSTEM_PROMPT = """You are ZICO's Travel Intent Router Agent.
Your role is to classify the user's travel request into exactly one operational category and extract relevant travel parameters.

Allowed Categories:
1. "HOTEL_SEARCH": Searching for hotels, resorts, hostels, homestays, accommodations, room rates, or lodging under a budget (e.g. "Hotels in Pune under 10k", "Where to stay in Paris", "Luxury resort in Goa"). MUST NEVER be classified as flight.
2. "FLIGHT_SEARCH": Searching for flight tickets, airline schedules, flight options, or booking routes between cities (e.g. "Find flights from Pune to Dubai tomorrow", "Flights to London").
3. "FLIGHT_STATUS": Real-time status, tracking, delays, gates, or terminal info for a specific flight (e.g. "Status of flight EK522", "Is my flight delayed?").
4. "DESTINATION_RESEARCH": Attractions, sightseeing, top places to visit, local customs, food recommendations, or city guides (e.g. "What are the best places to visit in Pune?", "Things to do in Tokyo").
5. "ITINERARY_PLANNING": Multi-day itineraries, day-by-day travel schedules (e.g. "Plan a 3-day trip to Bangalore").
6. "TRAVEL_POLICY": Baggage limits, visa regulations, cancellation rules, EU261 compensation, passport rules (e.g. "What is the baggage limit for Emirates?", "Do I need a visa for Japan?").
7. "LOCATION_QUERY": Geographic info, nearest airports, distance, transit between places (e.g. "What is the nearest airport to Munnar?").
8. "GENERAL_TRAVEL": Broad travel tips, packing advice, or general travel planning.
9. "UNSUPPORTED": Inquiries outside travel operations (software coding, math, medical, non-travel trivia).

Extraction Guidelines:
- location: Target city or region (e.g. "Pune" for "Hotels in Pune under 10k").
- budget: Budget constraint if specified (e.g. "10000 INR").
- origin / destination: Departure and arrival cities/airports for flight queries ONLY. Do NOT infer or invent missing origin/destination for hotel or general queries.
- Do NOT execute any tools. Return structured schema conforming to RouterDecision."""


# ---------------------------------------------------------------------------
# Structured Output Model
# ---------------------------------------------------------------------------


class RouterDecision(BaseModel):
    """
    Structured classification decision generated by the Router Agent.
    """

    intent: AllowedIntent = Field(description="The selected operational travel intent.")
    confidence: Optional[float] = Field(
        default=1.0,
        description="Heuristic model assessment of intent confidence (0.0 to 1.0).",
    )
    location: Optional[str] = Field(
        default=None,
        description="Target city, region, or country (e.g. 'Pune').",
    )
    origin: Optional[str] = Field(
        default=None,
        description="Departure location or airport for flight queries.",
    )
    destination: Optional[str] = Field(
        default=None,
        description="Arrival location or airport for flight queries.",
    )
    budget: Optional[str] = Field(
        default=None,
        description="Budget constraint (e.g. '10000 INR', 'under 10k').",
    )
    dates: Optional[str] = Field(
        default=None,
        description="Travel dates or timeframe if explicitly specified.",
    )
    reasoning: Optional[str] = Field(
        default=None,
        description="Short rationale explaining the routing classification.",
    )


# ---------------------------------------------------------------------------
# Heuristic Fallback Classifier
# ---------------------------------------------------------------------------


def classify_intent_heuristically(query: str) -> RouterDecision:
    """
    Deterministic intent classification and entity extraction fallback.
    Accurately identifies HOTEL_SEARCH, FLIGHT_SEARCH, FLIGHT_STATUS,
    DESTINATION_RESEARCH, ITINERARY_PLANNING, TRAVEL_POLICY, LOCATION_QUERY,
    GENERAL_TRAVEL, and UNSUPPORTED.
    """
    text = query.strip()
    lower = text.lower()

    # 1. Unsupported non-travel categories
    unsupported_patterns = [
        r"\b(?:python|javascript|typescript|c\+\+|html|css|sql|function|code|compile|bug|syntax)\b",
        r"\b(?:calculate|solve|equation|derivative|integral|math problem)\b",
        r"\b(?:symptoms|diagnosis|prescription|disease|doctor|medical advice)\b",
        r"\b(?:write an essay|write a poem|homework)\b",
    ]
    if any(re.search(p, lower) for p in unsupported_patterns):
        return RouterDecision(intent="UNSUPPORTED", confidence=1.0)

    # 2. Hotel Search (e.g. "Hotels in Pune under 10k", "Stay in Goa", "Resort in Manali")
    hotel_keywords = [
        "hotel",
        "hotels",
        "resort",
        "resorts",
        "hostel",
        "hostels",
        "homestay",
        "homestays",
        "stay in",
        "stays in",
        "accommodation",
        "accommodations",
        "motel",
        "motels",
        "lodging",
        "room in",
        "rooms in",
        "where to stay",
    ]
    if any(k in lower for k in hotel_keywords):
        loc = None
        loc_match = re.search(
            r"(?:hotels?|resorts?|hostels?|stays?|accommodations?|rooms?|lodging)\s+(?:in|at|near|around)\s+([a-zA-Z\s]+?)(?:\s+(?:under|below|within|budget|around|\b\d)|$)",
            lower,
        )
        if loc_match:
            loc = loc_match.group(1).strip().title()
        else:
            known_cities = [
                "pune",
                "mumbai",
                "delhi",
                "bangalore",
                "bengaluru",
                "goa",
                "hyderabad",
                "chennai",
                "kolkata",
                "kochi",
                "cochin",
                "jaipur",
                "manali",
                "shimla",
                "paris",
                "dubai",
                "london",
                "tokyo",
                "singapore",
                "new york",
                "munnar",
            ]
            for c in known_cities:
                if c in lower:
                    loc = c.title()
                    break

        budget = None
        budget_match = re.search(
            r"(?:under|below|within|budget(?:\s+of)?|max(?:\s+of)?|<=?)\s*(?:rs\.?|inr|\$|usd|eur|€)?\s*(\d+(?:,\d+)*(?:\.\d+)?)\s*(k|l|lakh|thousand)?\s*(inr|usd|eur|dollars|rupees|rs\.?)?",
            lower,
        )
        if budget_match:
            raw_num_str = budget_match.group(1).replace(",", "")
            multiplier = (budget_match.group(2) or "").lower()
            curr = (budget_match.group(3) or "").upper()
            if not curr:
                curr = (
                    "INR"
                    if (
                        "rs" in lower
                        or "inr" in lower
                        or "k" in multiplier
                        or "lakh" in multiplier
                        or not any(x in lower for x in ["$", "usd", "eur"])
                    )
                    else "USD"
                )
            try:
                num = float(raw_num_str)
                if multiplier == "k":
                    num *= 1000
                elif multiplier in ("l", "lakh"):
                    num *= 100000
                elif multiplier == "thousand":
                    num *= 1000
                budget = f"{int(num)} {curr}"
            except ValueError:
                budget = budget_match.group(0).strip()

        return RouterDecision(
            intent="HOTEL_SEARCH",
            location=loc,
            budget=budget,
            confidence=1.0,
            reasoning=f"Identified hotel accommodation request for {loc or 'specified location'}",
        )

    # 3. Flight Status (e.g. "Status of flight EK522", "Is my flight delayed?")
    flight_status_indicators = [
        "status of flight",
        "flight status",
        "check flight",
        "is my flight delayed",
        "flight delay",
        "track flight",
        "flight tracking",
    ]
    flight_code_match = re.search(r"\b([a-zA-Z0-9]{2,3})\s*(\d{2,4})\b", text)
    if any(k in lower for k in flight_status_indicators) or (
        flight_code_match and ("status" in lower or "delay" in lower)
    ):
        return RouterDecision(
            intent="FLIGHT_STATUS",
            confidence=1.0,
            reasoning="Identified flight status / tracking inquiry",
        )

    # 4. Flight Search (e.g. "Find flights from Pune to Dubai tomorrow")
    flight_search_indicators = [
        "flight",
        "flights",
        "fly to",
        "plane to",
        "airfare",
        "airline tickets",
    ]
    if any(k in lower for k in flight_search_indicators):
        origin, destination = None, None
        route_match = re.search(
            r"from\s+([a-zA-Z\s]+?)\s+to\s+([a-zA-Z\s]+?)(?:\s+(?:on|next|tomorrow|this|\b\d)|$)",
            lower,
        )
        if route_match:
            origin = route_match.group(1).strip().title()
            destination = route_match.group(2).strip().title()

        dates = None
        if "tomorrow" in lower:
            dates = "tomorrow"
        elif "next friday" in lower:
            dates = "next Friday"
        elif "next week" in lower:
            dates = "next week"

        return RouterDecision(
            intent="FLIGHT_SEARCH",
            origin=origin,
            destination=destination,
            dates=dates,
            confidence=1.0,
            reasoning="Identified flight search inquiry",
        )

    # 5. Destination Research (e.g. "What are the best places to visit in Pune?")
    research_indicators = [
        "places to visit",
        "things to do",
        "attractions",
        "sightseeing",
        "visit in",
        "must see in",
        "best spots in",
        "travel guide",
        "what to see",
    ]
    if any(k in lower for k in research_indicators):
        loc = None
        loc_match = re.search(
            r"(?:in|at|near|around)\s+([a-zA-Z\s]+?)(?:\s+(?:for|during|with)|$)", lower
        )
        if loc_match:
            loc = loc_match.group(1).strip().title()
        else:
            known_cities = [
                "pune",
                "mumbai",
                "delhi",
                "bangalore",
                "bengaluru",
                "goa",
                "paris",
                "dubai",
                "london",
                "tokyo",
                "munnar",
                "jaipur",
            ]
            for c in known_cities:
                if c in lower:
                    loc = c.title()
                    break

        return RouterDecision(
            intent="DESTINATION_RESEARCH",
            location=loc,
            confidence=1.0,
            reasoning=f"Identified destination research inquiry for {loc or 'specified destination'}",
        )

    # 6. Travel Policy (e.g. baggage, visa, cancellation)
    policy_indicators = [
        "baggage",
        "luggage",
        "visa",
        "passport",
        "policy",
        "cancellation",
        "eu261",
        "refund",
        "regulations",
        "duty of care",
    ]
    if any(k in lower for k in policy_indicators):
        return RouterDecision(
            intent="TRAVEL_POLICY",
            confidence=1.0,
            reasoning="Identified travel policy or regulatory inquiry",
        )

    # 7. Itinerary Planning
    itinerary_indicators = [
        "itinerary",
        "plan a trip",
        "plan my trip",
        "day trip",
        "3-day",
        "5-day",
        "7-day",
    ]
    if any(k in lower for k in itinerary_indicators):
        return RouterDecision(
            intent="ITINERARY_PLANNING",
            confidence=1.0,
            reasoning="Identified itinerary planning inquiry",
        )

    # 8. Location Query
    location_indicators = [
        "nearest airport",
        "how far",
        "distance between",
        "where is",
        "closest airport",
    ]
    if any(k in lower for k in location_indicators):
        return RouterDecision(
            intent="LOCATION_QUERY",
            confidence=1.0,
            reasoning="Identified geographic / location inquiry",
        )

    # 9. General Travel
    return RouterDecision(
        intent="GENERAL_TRAVEL",
        confidence=0.8,
        reasoning="General travel inquiry",
    )


# ---------------------------------------------------------------------------
# Router Agent Implementation
# ---------------------------------------------------------------------------


class RouterAgent:
    """
    Agent responsible for classifying user queries into operational travel intents.
    """

    def __init__(self, model: Optional[Any] = None) -> None:
        """
        Initialize the Router Agent.

        Args:
            model: Optional pre-configured chat model override (useful for testing).
                   If omitted, defaults to the centralized model from `get_chat_model()`.
        """
        self._model = model

    def _get_model(self) -> Any:
        """Resolve the active chat model instance."""
        if self._model is not None:
            return self._model
        return get_chat_model()

    def _decision_to_response(self, decision: RouterDecision) -> Dict[str, Any]:
        res: Dict[str, Any] = {
            "intent": decision.intent,
            "intent_confidence": decision.confidence,
            "active_agent": "router_agent",
        }
        if decision.location:
            res["location"] = decision.location
        if decision.budget:
            res["budget"] = decision.budget
        if decision.origin:
            res["origin"] = decision.origin
        if decision.destination:
            res["destination"] = decision.destination
        return res

    def route(self, state: TravelState) -> Dict[str, Any]:
        """
        Execute intent routing on the provided TravelState.

        Args:
            state: Active TravelState containing `user_query`.

        Returns:
            Partial state update dictionary containing `intent`, `intent_confidence`,
            and `active_agent`.
        """
        # 1. Validate user query
        user_query = (
            state.get("user_query")
            if isinstance(state, dict)
            else getattr(state, "user_query", None)
        )
        if not user_query or not isinstance(user_query, str) or not user_query.strip():
            logger.warning(
                "Router received empty or missing user query; classifying as unsupported."
            )
            return {
                "intent": "unsupported",
                "intent_confidence": None,
                "active_agent": "router_agent",
            }

        cleaned_query = user_query.strip()
        logger.info("Routing user request (query_len=%d)", len(cleaned_query))

        # 2. Obtain model
        try:
            model = self._get_model()
        except Exception as exc:
            logger.error("Failed to obtain chat model for routing: %s", exc)
            current_errors = list(state.get("errors", [])) if isinstance(state, dict) else []
            return {
                "intent": "unsupported",
                "intent_confidence": None,
                "active_agent": "router_agent",
                "errors": current_errors + [f"Router LLM configuration error: {exc}"],
            }

        # 3. Bind structured output schema
        if hasattr(model, "with_structured_output"):
            runnable = model.with_structured_output(RouterDecision)
        else:
            runnable = model

        # 4. Invoke model with structured prompt
        messages = [
            SystemMessage(content=ROUTER_SYSTEM_PROMPT),
            HumanMessage(content=cleaned_query),
        ]

        try:
            response = runnable.invoke(messages)
        except Exception as exc:
            logger.error("Router model invocation failed: %s", exc)
            err_str = str(exc).lower()
            if self._model is None and ("insufficient_quota" in err_str or "credit_balance_exhausted" in err_str):
                logger.warning("OpenAI quota exhausted; falling back to deterministic heuristic classification.")
                heuristic = classify_intent_heuristically(cleaned_query)
                return self._decision_to_response(heuristic)
            current_errors = list(state.get("errors", [])) if isinstance(state, dict) else []
            return {
                "intent": "unsupported",
                "intent_confidence": None,
                "active_agent": "router_agent",
                "errors": current_errors + [f"Router model failure: {exc}"],
            }

        # 5. Parse and validate structured output
        decision: Optional[RouterDecision] = None

        if isinstance(response, RouterDecision):
            decision = response
        elif isinstance(response, dict):
            try:
                decision = RouterDecision(**response)
            except Exception as exc:
                invalid_intent = str(response.get("intent", "unknown"))
                logger.warning(
                    "Router model returned invalid intent dictionary %r: %s", response, exc
                )
                current_errors = list(state.get("errors", [])) if isinstance(state, dict) else []
                return {
                    "intent": "unsupported",
                    "intent_confidence": None,
                    "active_agent": "router_agent",
                    "errors": current_errors
                    + [f"Invalid intent '{invalid_intent}'; fell back to unsupported."],
                }
        elif hasattr(response, "parsed"):
            parsed = getattr(response, "parsed")
            if isinstance(parsed, RouterDecision):
                decision = parsed
            elif isinstance(parsed, dict):
                try:
                    decision = RouterDecision(**parsed)
                except Exception:
                    decision = None

        if decision is None:
            logger.error("Router received unparseable response structure: %r", response)
            current_errors = list(state.get("errors", [])) if isinstance(state, dict) else []
            return {
                "intent": "unsupported",
                "intent_confidence": None,
                "active_agent": "router_agent",
                "errors": current_errors + ["Model failed to produce a valid RouterDecision."],
            }

        # 6. Strict validation against allowed intents
        if decision.intent not in ALLOWED_INTENTS:
            logger.warning("Router received intent %r outside allowed categories.", decision.intent)
            current_errors = list(state.get("errors", [])) if isinstance(state, dict) else []
            return {
                "intent": "unsupported",
                "intent_confidence": None,
                "active_agent": "router_agent",
                "errors": current_errors
                + [f"Unrecognized intent '{decision.intent}'; fell back to unsupported."],
            }

        logger.info(
            "Router selected intent: %s (confidence=%s)", decision.intent, decision.confidence
        )

        return self._decision_to_response(decision)

    async def aroute(self, state: TravelState) -> Dict[str, Any]:
        """
        Asynchronously execute intent routing on the provided TravelState.

        Args:
            state: Active TravelState containing `user_query`.

        Returns:
            Partial state update dictionary.
        """
        # 1. Validate user query
        user_query = (
            state.get("user_query")
            if isinstance(state, dict)
            else getattr(state, "user_query", None)
        )
        if not user_query or not isinstance(user_query, str) or not user_query.strip():
            logger.warning(
                "Router received empty or missing user query; classifying as unsupported."
            )
            return {
                "intent": "unsupported",
                "intent_confidence": None,
                "active_agent": "router_agent",
            }

        cleaned_query = user_query.strip()
        logger.info("Routing user request asynchronously (query_len=%d)", len(cleaned_query))

        # 2. Obtain model
        try:
            model = self._get_model()
        except Exception as exc:
            logger.error("Failed to obtain chat model for routing: %s", exc)
            current_errors = list(state.get("errors", [])) if isinstance(state, dict) else []
            return {
                "intent": "unsupported",
                "intent_confidence": None,
                "active_agent": "router_agent",
                "errors": current_errors + [f"Router LLM configuration error: {exc}"],
            }

        # 3. Bind structured output schema
        if hasattr(model, "with_structured_output"):
            runnable = model.with_structured_output(RouterDecision)
        else:
            runnable = model

        # 4. Invoke model asynchronously
        messages = [
            SystemMessage(content=ROUTER_SYSTEM_PROMPT),
            HumanMessage(content=cleaned_query),
        ]

        try:
            if hasattr(runnable, "ainvoke"):
                response = await runnable.ainvoke(messages)
            else:
                response = runnable.invoke(messages)
        except Exception as exc:
            logger.error("Router async model invocation failed: %s", exc)
            err_str = str(exc).lower()
            if self._model is None and ("insufficient_quota" in err_str or "credit_balance_exhausted" in err_str):
                logger.warning("OpenAI quota exhausted; falling back to deterministic heuristic classification.")
                heuristic = classify_intent_heuristically(cleaned_query)
                return self._decision_to_response(heuristic)
            current_errors = list(state.get("errors", [])) if isinstance(state, dict) else []
            return {
                "intent": "unsupported",
                "intent_confidence": None,
                "active_agent": "router_agent",
                "errors": current_errors + [f"Router model failure: {exc}"],
            }

        # 5. Parse and validate structured output
        decision: Optional[RouterDecision] = None
        if isinstance(response, RouterDecision):
            decision = response
        elif isinstance(response, dict):
            try:
                decision = RouterDecision(**response)
            except Exception:
                invalid_intent = str(response.get("intent", "unknown"))
                current_errors = list(state.get("errors", [])) if isinstance(state, dict) else []
                return {
                    "intent": "unsupported",
                    "intent_confidence": None,
                    "active_agent": "router_agent",
                    "errors": current_errors
                    + [f"Invalid intent '{invalid_intent}'; fell back to unsupported."],
                }
        elif hasattr(response, "parsed"):
            parsed = getattr(response, "parsed")
            if isinstance(parsed, RouterDecision):
                decision = parsed
            elif isinstance(parsed, dict):
                try:
                    decision = RouterDecision(**parsed)
                except Exception:
                    decision = None

        if decision is None or decision.intent not in ALLOWED_INTENTS:
            unrec = decision.intent if decision else "unparseable"
            logger.warning("Router received invalid intent %r.", unrec)
            current_errors = list(state.get("errors", [])) if isinstance(state, dict) else []
            return {
                "intent": "unsupported",
                "intent_confidence": None,
                "active_agent": "router_agent",
                "errors": current_errors
                + [f"Unrecognized intent '{unrec}'; fell back to unsupported."],
            }

        logger.info(
            "Router selected intent: %s (confidence=%s)", decision.intent, decision.confidence
        )

        return self._decision_to_response(decision)


# ---------------------------------------------------------------------------
# Module-level Convenience Functions (LangGraph Node Interface)
# ---------------------------------------------------------------------------


def route_request(state: TravelState, llm: Optional[Any] = None) -> Dict[str, Any]:
    """
    Synchronous LangGraph node function for request intent routing.

    Args:
        state: Active TravelState containing `user_query`.
        llm: Optional pre-configured chat model override.

    Returns:
        Partial state update dictionary containing classified `intent`.
    """
    agent = RouterAgent(model=llm)
    return agent.route(state)


async def aroute_request(state: TravelState, llm: Optional[Any] = None) -> Dict[str, Any]:
    """
    Asynchronous LangGraph node function for request intent routing.

    Args:
        state: Active TravelState containing `user_query`.
        llm: Optional pre-configured chat model override.

    Returns:
        Partial state update dictionary containing classified `intent`.
    """
    agent = RouterAgent(model=llm)
    return await agent.aroute(state)
